# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFhmcuT6OAFEAcSFy3XA1C00rWogfaxF
"""

# src/analysis.py
import pandas as pd

def trader_sentiment_insights(df):
    # Determine if each trade was a win or loss
    df['is_win'] = df['closedPnL'] > 0

    # Group by sentiment
    sentiment_stats = df.groupby('sentiment').agg(
        avg_pnl=('closedPnL', 'mean'),
        win_rate=('is_win', 'mean'),
        trade_count=('closedPnL', 'count')
    ).reset_index()

    return sentiment_stats