# -*- coding: utf-8 -*-
"""preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpprK_6twSZ_DQCpglRDNfuUh7ZA1u9s
"""

# src/preprocess.py
import pandas as pd

def load_and_preprocess_data(trader_path, sentiment_path):
    # Load trader data
    trader_df = pd.read_csv(trader_path)
    sentiment_df = pd.read_csv(sentiment_path)

    # Convert time columns to datetime
    trader_df['time'] = pd.to_datetime(trader_df['time'])
    sentiment_df['Date'] = pd.to_datetime(sentiment_df['Date'])

    # Clean sentiment column
    sentiment_df['Classification'] = sentiment_df['Classification'].str.strip().str.lower()

    # Merge based on date (assuming daily aggregation)
    trader_df['date'] = trader_df['time'].dt.date
    sentiment_df['date'] = sentiment_df['Date'].dt.date

    merged_df = pd.merge(trader_df, sentiment_df[['date', 'Classification']], on='date', how='left')
    merged_df.rename(columns={'Classification': 'sentiment'}, inplace=True)

    return merged_df, sentiment_df