# -*- coding: utf-8 -*-
"""viz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6srWRqLNnoD_O8QQjPIkTRP3kBRYqtM
"""

# src/viz.py
import matplotlib.pyplot as plt
import seaborn as sns

def plot_pnl_distribution(df):
    plt.figure(figsize=(10, 6))
    sns.histplot(data=df, x='closedPnL', hue='sentiment', kde=True, bins=50)
    plt.title('PnL Distribution by Market Sentiment')
    plt.xlabel('Closed PnL')
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def plot_winrate_by_sentiment(insight_df):
    plt.figure(figsize=(8, 5))
    sns.barplot(data=insight_df, x='sentiment', y='win_rate', palette='Set2')
    plt.title('Average Win Rate by Market Sentiment')
    plt.ylabel('Win Rate')
    plt.xlabel('Sentiment')
    plt.grid(True)
    plt.tight_layout()
    plt.show()